/**
 * Tests for FDB-OPS-002: Security & Compliance Controls
 */
import { describe, it, expect, beforeEach } from 'vitest';
import { getSecurityControlsService, resetSecurityControlsForTest, DEFAULT_ENCRYPTION_POLICY } from '../src/security';

describe('Security Controls Service', () => {
  beforeEach(() => {
    resetSecurityControlsForTest();
  });

  it('should return default encryption policy when none set', () => {
    const sc = getSecurityControlsService();
    const policy = sc.getEncryptionPolicy('t1', 'mongodb');
    expect(policy.atRest).toBe(DEFAULT_ENCRYPTION_POLICY.atRest);
    expect(policy.inTransit).toBe(true);
  });

  it('should set and retrieve encryption policy', () => {
    const sc = getSecurityControlsService();
    sc.setEncryptionPolicy('t1', 'mongodb', { atRest: 'customer_managed', inTransit: true, fieldLevelFields: ['ssn'] });
    const policy = sc.getEncryptionPolicy('t1', 'mongodb');
    expect(policy.atRest).toBe('customer_managed');
    expect(policy.fieldLevelFields).toContain('ssn');
  });

  it('should validate encryption — compliant', () => {
    const sc = getSecurityControlsService();
    sc.setEncryptionPolicy('t1', 'mongodb', { atRest: 'provider_managed', inTransit: true, fieldLevelFields: [] });
    const result = sc.validateEncryption('t1', 'mongodb');
    expect(result.compliant).toBe(true);
    expect(result.issues).toHaveLength(0);
  });

  it('should validate encryption — non-compliant', () => {
    const sc = getSecurityControlsService();
    sc.setEncryptionPolicy('t1', 'mongodb', { atRest: 'none', inTransit: false, fieldLevelFields: [] });
    const result = sc.validateEncryption('t1', 'mongodb');
    expect(result.compliant).toBe(false);
    expect(result.issues.length).toBe(2);
  });

  it('should set and validate access boundaries', () => {
    const sc = getSecurityControlsService();
    sc.setAccessBoundary({
      tenantId: 't1',
      provider: 'mongodb',
      allowedRegions: ['us-east-1', 'eu-west-1'],
      allowedIpRanges: ['10.0.0.0/8'],
      requireMfa: true,
      maxSessionDurationMinutes: 60,
    });

    const allowed = sc.validateAccess('t1', 'mongodb', 'us-east-1', '10.0.1.5');
    expect(allowed.allowed).toBe(true);

    const denied = sc.validateAccess('t1', 'mongodb', 'ap-southeast-1');
    expect(denied.allowed).toBe(false);
    expect(denied.reason).toContain('not in allowed regions');
  });

  it('should allow access when no boundary configured', () => {
    const sc = getSecurityControlsService();
    const result = sc.validateAccess('t1', 'mongodb', 'any-region');
    expect(result.allowed).toBe(true);
  });

  it('should generate compliance report', () => {
    const sc = getSecurityControlsService();
    sc.setEncryptionPolicy('t1', 'mongodb', { atRest: 'provider_managed', inTransit: true, fieldLevelFields: [] });
    sc.setAccessBoundary({
      tenantId: 't1',
      provider: 'mongodb',
      allowedRegions: ['us-east-1'],
      allowedIpRanges: [],
      requireMfa: false,
      maxSessionDurationMinutes: 120,
    });

    const report = sc.generateComplianceReport('t1', 'mongodb');
    expect(report.tenantId).toBe('t1');
    expect(report.encryptionCompliant).toBe(true);
    expect(report.accessBoundaryCompliant).toBe(true);
    expect(report.auditTrailComplete).toBe(true); // events generated by setEncryptionPolicy/setAccessBoundary
  });

  it('should record and retrieve audit events', () => {
    const sc = getSecurityControlsService();
    sc.recordEvent({
      type: 'credential_created',
      tenantId: 't1',
      actor: 'admin',
      provider: 'mongodb',
      details: { credId: 'cred-1' },
      severity: 'info',
    });

    const events = sc.getEventsByTenant('t1');
    expect(events.length).toBeGreaterThanOrEqual(1);
    expect(events[0].type).toBe('credential_created');
  });

  it('should retrieve events by type', () => {
    const sc = getSecurityControlsService();
    sc.recordEvent({ type: 'access_denied', tenantId: 't1', actor: 'system', details: {}, severity: 'warning' });
    sc.recordEvent({ type: 'access_granted', tenantId: 't2', actor: 'system', details: {}, severity: 'info' });

    const denied = sc.getEventsByType('access_denied');
    expect(denied.length).toBe(1);
    expect(denied[0].tenantId).toBe('t1');
  });

  it('should retrieve critical events', () => {
    const sc = getSecurityControlsService();
    sc.recordEvent({ type: 'unauthorized_access_attempt', tenantId: 't1', actor: 'hacker', details: {}, severity: 'critical' });
    sc.recordEvent({ type: 'access_granted', tenantId: 't2', actor: 'user', details: {}, severity: 'info' });

    const critical = sc.getCriticalEvents();
    expect(critical.length).toBe(1);
    expect(critical[0].severity).toBe('critical');
  });
});
