/**
 * Report Templates
 * 
 * Customizable templates for compliance reports
 */

import { Report, ReportType } from './types';

export interface ReportTemplate {
  type: ReportType;
  name: string;
  description: string;
  sections: ReportSection[];
  branding?: BrandingOptions;
}

export interface ReportSection {
  id: string;
  title: string;
  description?: string;
  dataKey: string;
  renderer: 'table' | 'chart' | 'text' | 'list' | 'metrics';
  config?: any;
}

export interface BrandingOptions {
  logo_url?: string;
  company_name?: string;
  primary_color?: string;
  secondary_color?: string;
  footer_text?: string;
}

export class ReportTemplateManager {
  private templates: Map<ReportType, ReportTemplate> = new Map();

  constructor() {
    this.initializeDefaultTemplates();
  }

  /**
   * Get template for report type
   */
  getTemplate(type: ReportType): ReportTemplate | undefined {
    return this.templates.get(type);
  }

  /**
   * Register custom template
   */
  registerTemplate(template: ReportTemplate): void {
    this.templates.set(template.type, template);
  }

  /**
   * Render report using template
   */
  async render(
    report: Report,
    format: 'html' | 'pdf' | 'json' | 'csv',
    branding?: BrandingOptions
  ): Promise<string | Buffer> {
    const template = this.getTemplate(report.type);
    if (!template) {
      throw new Error(`No template found for report type: ${report.type}`);
    }

    switch (format) {
      case 'html':
        return this.renderHTML(report, template, branding);
      case 'pdf':
        return this.renderPDF(report, template, branding);
      case 'json':
        return this.renderJSON(report);
      case 'csv':
        return this.renderCSV(report, template);
      default:
        throw new Error(`Unsupported format: ${format}`);
    }
  }

  /**
   * Render HTML report
   */
  private renderHTML(
    report: Report,
    template: ReportTemplate,
    branding?: BrandingOptions
  ): string {
    const brand = branding || template.branding || {};
    
    let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${template.name} - ${report.generated_at.toISOString()}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      color: #333;
    }
    .header {
      border-bottom: 3px solid ${brand.primary_color || '#007bff'};
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .logo {
      max-width: 200px;
      margin-bottom: 10px;
    }
    .title {
      font-size: 28px;
      font-weight: bold;
      color: ${brand.primary_color || '#007bff'};
    }
    .subtitle {
      font-size: 14px;
      color: #666;
      margin-top: 5px;
    }
    .section {
      margin-bottom: 40px;
    }
    .section-title {
      font-size: 20px;
      font-weight: bold;
      margin-bottom: 15px;
      color: ${brand.secondary_color || '#333'};
    }
    .metrics {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin-bottom: 20px;
    }
    .metric {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      border-left: 4px solid ${brand.primary_color || '#007bff'};
    }
    .metric-label {
      font-size: 12px;
      color: #666;
      text-transform: uppercase;
    }
    .metric-value {
      font-size: 32px;
      font-weight: bold;
      color: #333;
      margin-top: 5px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    th {
      background: #f8f9fa;
      font-weight: bold;
    }
    .footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      font-size: 12px;
      color: #666;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    ${brand.logo_url ? `<img src="${brand.logo_url}" class="logo" alt="Logo">` : ''}
    <div class="title">${template.name}</div>
    <div class="subtitle">
      Generated: ${report.generated_at.toISOString()}<br>
      Period: ${report.period.start.toISOString()} to ${report.period.end.toISOString()}
    </div>
  </div>
`;

    // Render sections
    for (const section of template.sections) {
      html += this.renderSection(section, report.data);
    }

    html += `
  <div class="footer">
    ${brand.footer_text || `Generated by ${brand.company_name || 'Compliance System'}`}
  </div>
</body>
</html>
`;

    return html;
  }

  /**
   * Render section
   */
  private renderSection(section: ReportSection, data: any): string {
    const sectionData = data[section.dataKey];
    if (!sectionData) {
      return '';
    }

    let content = `
  <div class="section">
    <div class="section-title">${section.title}</div>
    ${section.description ? `<p>${section.description}</p>` : ''}
`;

    switch (section.renderer) {
      case 'metrics':
        content += this.renderMetrics(sectionData);
        break;
      case 'table':
        content += this.renderTable(sectionData);
        break;
      case 'list':
        content += this.renderList(sectionData);
        break;
      case 'text':
        content += `<p>${sectionData}</p>`;
        break;
    }

    content += `
  </div>
`;

    return content;
  }

  /**
   * Render metrics
   */
  private renderMetrics(data: any): string {
    let html = '<div class="metrics">';
    
    for (const [key, value] of Object.entries(data)) {
      const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
      html += `
      <div class="metric">
        <div class="metric-label">${label}</div>
        <div class="metric-value">${value}</div>
      </div>
`;
    }
    
    html += '</div>';
    return html;
  }

  /**
   * Render table
   */
  private renderTable(data: any[]): string {
    if (!Array.isArray(data) || data.length === 0) {
      return '<p>No data available</p>';
    }

    const headers = Object.keys(data[0]);
    
    let html = '<table><thead><tr>';
    for (const header of headers) {
      const label = header.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
      html += `<th>${label}</th>`;
    }
    html += '</tr></thead><tbody>';

    for (const row of data) {
      html += '<tr>';
      for (const header of headers) {
        html += `<td>${row[header]}</td>`;
      }
      html += '</tr>';
    }

    html += '</tbody></table>';
    return html;
  }

  /**
   * Render list
   */
  private renderList(data: any[]): string {
    if (!Array.isArray(data) || data.length === 0) {
      return '<p>No items</p>';
    }

    let html = '<ul>';
    for (const item of data) {
      html += `<li>${typeof item === 'string' ? item : JSON.stringify(item)}</li>`;
    }
    html += '</ul>';
    return html;
  }

  /**
   * Render PDF report
   */
  private async renderPDF(
    report: Report,
    template: ReportTemplate,
    branding?: BrandingOptions
  ): Promise<Buffer> {
    // TODO: Implement PDF generation using pdfkit or puppeteer
    const html = this.renderHTML(report, template, branding);
    return Buffer.from(html);
  }

  /**
   * Render JSON report
   */
  private renderJSON(report: Report): string {
    return JSON.stringify(report, null, 2);
  }

  /**
   * Render CSV report
   */
  private renderCSV(report: Report, template: ReportTemplate): string {
    // TODO: Implement CSV generation
    return 'CSV export not yet implemented';
  }

  /**
   * Initialize default templates
   */
  private initializeDefaultTemplates(): void {
    // Security Summary Template
    this.templates.set('security_summary', {
      type: 'security_summary',
      name: 'Security Summary Report',
      description: 'Overview of authentication, authorization, and security events',
      sections: [
        {
          id: 'overview',
          title: 'Overview',
          dataKey: 'overview',
          renderer: 'metrics',
        },
        {
          id: 'authentication',
          title: 'Authentication Events',
          dataKey: 'authentication',
          renderer: 'metrics',
        },
        {
          id: 'authorization',
          title: 'Authorization Events',
          dataKey: 'authorization',
          renderer: 'metrics',
        },
        {
          id: 'security_events',
          title: 'Security Events',
          dataKey: 'security_events',
          renderer: 'table',
        },
      ],
    });

    // GDPR Compliance Template
    this.templates.set('gdpr_compliance', {
      type: 'gdpr_compliance',
      name: 'GDPR Compliance Report',
      description: 'Data subject requests, consent, and retention compliance',
      sections: [
        {
          id: 'summary',
          title: 'Summary',
          dataKey: 'summary',
          renderer: 'metrics',
        },
        {
          id: 'data_subject_requests',
          title: 'Data Subject Requests',
          dataKey: 'data_subject_requests',
          renderer: 'table',
        },
        {
          id: 'consent_status',
          title: 'Consent Status',
          dataKey: 'consent_status',
          renderer: 'metrics',
        },
      ],
    });

    // Access Audit Template
    this.templates.set('access_audit', {
      type: 'access_audit',
      name: 'Access Audit Report',
      description: 'Detailed audit of data access and admin actions',
      sections: [
        {
          id: 'summary',
          title: 'Summary',
          dataKey: 'summary',
          renderer: 'metrics',
        },
        {
          id: 'access_events',
          title: 'Access Events',
          dataKey: 'access_events',
          renderer: 'table',
        },
      ],
    });

    // Data Retention Template
    this.templates.set('data_retention', {
      type: 'data_retention',
      name: 'Data Retention Report',
      description: 'Data retention policy execution and results',
      sections: [
        {
          id: 'summary',
          title: 'Summary',
          dataKey: 'summary',
          renderer: 'metrics',
        },
        {
          id: 'policies',
          title: 'Retention Policies',
          dataKey: 'policies',
          renderer: 'table',
        },
      ],
    });

    // SOC 2 Readiness Template
    this.templates.set('soc2_readiness', {
      type: 'soc2_readiness',
      name: 'SOC 2 Readiness Report',
      description: 'SOC 2 control compliance status',
      sections: [
        {
          id: 'summary',
          title: 'Summary',
          dataKey: 'summary',
          renderer: 'metrics',
        },
        {
          id: 'controls',
          title: 'Control Status',
          dataKey: 'controls',
          renderer: 'table',
        },
        {
          id: 'issues',
          title: 'Outstanding Issues',
          dataKey: 'issues',
          renderer: 'table',
        },
      ],
    });
  }
}

export const reportTemplateManager = new ReportTemplateManager();
